### ISSUE TITLE
New name for the package and maybe register?

### ISSUE THREAD

**Issue by meggart** [JuliaDataCubes/EarthDataLab.jl#141]
@mafla @gdkrmr @felixcremer 

I am thinking about registering this package in the General Julia registry, so that it can be installed more easily by every user. To do this, we would have to change the name to something more descriptive, because ESDL is not a widely spread abbreviation. So in case you agree that registration is a good idea I would be open to package name suggestions. Some ideas are:

- EarthSystemDataLab.jl
- EarthSystemArrays.jl
- YArray.jl
- something completely unrelated like name of your cat etc...?

**Comment by Balinus** [comment]
> * EarthSystemArrays.jl

I really like this name. I'ts more generic than `EarthSystemDataLab`. 

Just my 2 cents!

**Comment by gdkrmr** [comment]
I think the `Lab` part is fine, because it contains functionality for analysis. So i go with `EarthSystemDataLab.jl`

**Comment by meggart** [comment]
As suggested by @felixcremer one could also move stuff which is not Geo-related to a core package and call this YAXArrays (acronym for Yet Another Xarray), which I find not too bad. It is not too long and should not be controversial in reserving a popular name. Then we could move all the Geo-related stuff like computing mean annual cycles, CF conventions for Time Axes etc to its own package and call this EarthSystemDataLab.

**Comment by Balinus** [comment]
Hello, 

is there any plan for tagging? I would like to use use ESDL as the backend for ClimateTools.jl. As far as I understand, package dependence needs to be registered? Or I would perhaps work directly into EarthSystemDataLab.

No worries about the timeline, I won't work on this until September I guess. I was just wondering! :)

Cheers!

**Comment by meggart** [comment]
Yes, I am back to work and the first thing on my list is to get ESDL spllit and registered. I hope to finish this within a month.

**Comment by MartinuzziFrancesco** [comment]
renamed in #274 and registration process started [PR](https://github.com/JuliaRegistries/General/pull/59566)
