### ISSUE TITLE
Split Docs

### ISSUE THREAD

**Issue by MartinuzziFrancesco** [JuliaDataCubes/EarthDataLab.jl#261]
At the moment the docs are referencing some methods and functions that have been moved to [YAXArrays.jl](https://github.com/meggart/YAXArrays.jl). 

The current documentation also documents [ESDLPlots.jl](https://github.com/esa-esdl/ESDLPlots.jl) and while it is useful it think a more clear distinction could be more helpful to those encountering the package for the first time.

I have started to tackle both issues locally and I will push a very basic PR in the next days to start the split.

**Comment by felixcremer** [comment]
Yes that is definitively needed. It would be great, when you could start this with a PR. 
See also https://github.com/meggart/YAXArrays.jl/issues/38. Feel free to add topics there that are missing in the documentation.

**Comment by meggart** [comment]
I can only second what @felixcremer said, thanks a lot for starting to help on fixing the very messy documentation

**Comment by MartinuzziFrancesco** [comment]
I believe this was addressed by #266
