### ISSUE TITLE
Incompatible with YAXArrays = "0.5"?

### ISSUE THREAD

**Issue by BernhardAhrens** [JuliaDataCubes/EarthDataLab.jl#299]
I have both EarthDataLab and YAXArrays in my project. EarthDataLab prevents update of YAXArrays since compat is YAXArrays = "0.4". I am wondering if EarthDataLab is indeed incompatible with YAXArrays 0.5?

**Comment by felixcremer** [comment]
Yes, it was incompatible with YAXArrays 0.5. Fabian merged the pull request that pushes EarthDataLab to YAXArrays 0.5 today and it is currently registered.

**Comment by felixcremer** [comment]
The new version is now registered.
